### ISSUE TITLE
can't authenticate with vimeo

### ISSUE THREAD

**Issue by brianwebb01** [matthooks/vimeo#4]
I'm getting an exception when vimeo redirects to my callback method:

401 Unauthorized  => OAuth::Unauthorized in VimeoController#vimeo_callback 

Any ideas?  

On a side note, I added config.gem "vimeo" to my environment.rb but kept getting crashes saying that oauth_client couldn't be found.  I looked in the gem folder oauth-0.3.6 and didn't see oauth_client, just oauth, so I changed vimeo.rb #7 to be require "oauth" instead and got rid of the crash.  I wonder if it is causing the authentication error though....

Here's the stacktrace:

/Library/Ruby/Gems/1.8/gems/oauth-0.3.6/lib/oauth/consumer.rb:200:in `token_request'
/Library/Ruby/Gems/1.8/gems/oauth-0.3.6/lib/oauth/tokens/request_token.rb:18:in`get_access_token'
/Library/Ruby/Gems/1.8/gems/vimeo-1.1.0/lib/vimeo/advanced/base.rb:79:in `get_access_token'
/Users/brian/Sites/vsblog/app/controllers/vimeo_controller.rb:17:in`vimeo_callback'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in `send'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in`perform_action_without_filters'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:617:in `call_filters'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:610:in`perform_action_without_benchmark'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in`ms'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/flash.rb:146:in`perform_action'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `send'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in`process_without_filters'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `process'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:391:in`process'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:386:in `call'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:437:in`call'

**Comment by xpahbs** [comment]
The same, i'm get 401 Unauthorized

**Comment by tuanhv258** [comment]
I have the same problem when I use request_token = base.get_request_token affter I create base = Vimeo::Advanced::Base.new. Anyone can help me?
