### ISSUE TITLE
Installed gem and can't run (Newbie Question)

### ISSUE THREAD

**Issue by rfdlp** [matthooks/vimeo#6]
Hello Buddies!

I don't know if it's the right place to post it, so, if it's not, sorry. 

I installed the gem (gem install vimeo) and it all goes smoothly, but when I load my console and type: Vimeo - it gives me: 
NameError: uninitialized constant Vimeo

Information that would be usefull:
- I'm using Ubuntu 10.04
- When I install the gem it gives me:
  root@ubuntu:/home/rafael/Rails/seekr# gem install vimeo
  Successfully installed vimeo-1.2.0
  1 gem installed
  Installing ri documentation for vimeo-1.2.0...
  Installing RDoc documentation for vimeo-1.2.0...
  Could not find main page README.rdoc
  Could not find main page README.rdoc
  Could not find main page README.rdoc
  Could not find main page README.rdoc

What may I be doing wrong?
- I have other gems installed (Twitter as an example) and it works perfectly.

Thanks in advance!

**Comment by xpahbs** [comment]
I like to now if the gem still works in api vimeo v3?
