### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by colby-swandale** [matthooks/vimeo#62]
@matthooks, I was wanting to know if you are still maintaining this gem. I can see some Issues and PRs that are quite old and outdated. Vimeo's API v2 is also deprecated and i see no clear indication of any work for v3 being done.

I am starting work on a ruby project that relies on Vimeo and I would hate to start from scratch. I will be happy to put some time down on working to bring this gem up to date with everything, do you want me to start sending some PRs your way or just give me commit bit if you prefer.

Happy to talk more.

**Comment by matthooks** [comment]
I'll hook you up with a commit bit.
