### ISSUE TITLE
/me/* endpoints

### ISSUE THREAD

**Issue by ryanburnette** [matthooks/vimeo#64]
I'm trying to access some content that I can only get from the `/me/*` endpoints. I read the source a bit but wasn't clear how the `create_api_method` method was determining the associated endpoint. Perhaps I just don't understand how this plugin is accessing the API. Am I correct that there is no current way to access the `/me/*` endpoints?

**Comment by colby-swandale** [comment]
the `/me/*` functions are part of the Vimeo V3 API, the current release of the gem is using V2 so you won't ever reach it. I am working on implementing V3 at the moment, see #63

**Comment by ryanburnette** [comment]
I didn't notice that I was in the v3 docs when I read about `/me/*`. Sorry about that. Amazing work on #63 so far.

**Comment by colby-swandale** [comment]
Hi everyone,

Anyone keeping an eye on this PR would have noticed that i have not made any commits for quite some time. Don't worry i have not abandoned this project, my only computer died a few weeks back and had to wait for a replacement to arrive. Numerous personal events has also eaten most of the my spare time that i can allocate to this project but i now will start putting some time down again to work on this.

Thanks guys!
