### ISSUE TITLE
Problem with using vimeo and  speaker text caption box 

### ISSUE THREAD

**Issue by karunakarkarna** [matthooks/vimeo#65]
I am getting a problem with vimeo and captionbox  SpeakerText ,
While running the video, the  transcripts are not getting highlighted and at the same time search, font size button  are not working(total Stbar is not working ) , can you please provide any suggestions for this.  

sample code:

 <html>
<head id="Head1" runat="server">
<title></title>
</head>
       <script src="jquery-1.11.3.min.js"></script>
      <script src='jquery-1.7.1.js' type='text/javascript'></script>
 <script type='text/javascript' src='jquery.captionbox.js' ></script>
      
<link rel="stylesheet" type="text/css" href="css.css">
<link href="captionbox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="jquery.captionbox.js" type="text/javascript"></script> 
<script src="froogaloop.min.js" type="text/javascript"></script> 
<script src="sha1.js" type="text/javascript"></script> 

<script src="swfobject.js" type="text/javascript"></script> 
 <body>
<div>

<div class="ooyalaPlayerDiv">
<object id="STautoID1" class="STvideoPlayer" width="425" height="344" type="application/x-shockwave-flash" name="STautoID1" data="http://www.youtube.com/v/RyNAxydJ4G8&fs=1?&rel=0&showinfo=0&enablejsapi=1&playerapiid=STautoID1" style="visibility: visible;">
<param name="allowFullScreen" value="true">
<param name="allowscriptaccess" value="always">
<param name="allowScriptAccess" value="always">
</object>
<div id="STtranscriptEmbed_1_RyNAxydJ4G8" class="STplayer visibleTranscript narrow" data-hash="SgWXr31Uin" data-version="1.0" style="width: 425px; margin-left: 0px;">
<div class="STbar">
<div class="STlogo"></div>
<input class="STsearchField empty" type="text">
<div class="STsearchPrevButton empty STdisplayWithTranscript"></div>
<div class="STsearchNextButton empty STdisplayWithTranscript"></div>
<div class="STfontSizeButton STdisplayWithTranscript"></div>
<div class="STautoScroll STdisplayWithTranscript off">AUTO SCROLL</div>
<div class="STshowText">EXPAND TRANSCRIPT</div>
</div>
<div class="STembedWrapper" style="width: 425px;">
<div class="STsharePane STdisplayWithTranscript STsharePaneActive" style="height: 224px;">
<span class="STsharePaneText">
<a class="STtwitterShare STxShare" onclick="if(stjQuery(this).data(STCONST_DATAKEY_QUOTELINK_TEXT) != '') { temp = window.open('','_blank','width=550,height=420'); stjQuery(this).STtwitterShare(temp); }" onmousedown="stjQuery(this).STcaptureQuoteLink()"></a>
<a class="STfacebookShare STxShare" onclick="if(stjQuery(this).data(STCONST_DATAKEY_QUOTELINK_TEXT) != '') { temp = window.open('','_blank'); stjQuery(this).STfacebookShare(temp); }" onmousedown="stjQuery(this).STcaptureQuoteLink()"></a>
<a class="STurlShare STxShare" onclick="if(stjQuery(this).data(STCONST_DATAKEY_QUOTELINK_TEXT) != '') { stjQuery(this).STurlShare(); }" onmousedown="stjQuery(this).STcaptureQuoteLink()"></a>
<br>
</div>
<div class="STtranscriptPane">
<div class="STscrollBar">
<div class="STscrollUp"></div>
<div class="STscrollVisible" style="height: 55.2308px; top: 6.47401px;">
<div class="STscrollTop"></div>
<div class="STscrollBottom"></div>
</div>
<div class="STscrollDown"></div>
</div>
<div class="STtranscriptWrapper" tabindex="100" style="height: 210px;">
<div class="STtranscriptDisplay" style="top: -32px;">
<span id="STtranscriptContent1" class="STtranscriptContent STcurrentContent" name="970">Online video is transforming the </span>
<span id="STtranscriptContent2" class="STtranscriptContent" name="2650">way we learn, communicate, collaborate, </span>
<span id="STtranscriptContent3" class="STtranscriptContent" name="5180">and consume information everyday. </span>
<span id="STtranscriptContent4" class="STtranscriptContent" name="8060">Meet John, his company is leveraging videos for online learning. </span>
<span id="STtranscriptContent5" class="STtranscriptContent" name="11710">As the number of courses grows, </span>
<span id="STtranscriptContent6" class="STtranscriptContent" name="13480">finding and delivering relevant </span>
<span id="STtranscriptContent7" class="STtranscriptContent" name="14880">content to his users is becoming more difficult. </span>
<span id="STtranscriptContent8" class="STtranscriptContent" name="17710">On top of that, he is </span>
<span id="STtranscriptContent9" class="STtranscriptContent" name="19070">
<span id="STtranscriptContent10" class="STtranscriptContent" name="22080">John knows that the best way </span>
<span id="STtranscriptContent11" class="STtranscriptContent" name="23330">to make his videos discoverable, and </span>
<span id="STtranscriptContent12" class="STtranscriptContent" name="25310">accessible is through transcription. </span>
<span id="STtranscriptContent13" class="STtranscriptContent" name="27550">Initially, John hired in-house </span>
<span id="STtranscriptContent14" class="STtranscriptContent" name="29300">employees to transcribe all their videos. </span>
<span id="STtranscriptContent15" class="STtranscriptContent" name="31740">The results were good. </span>
<span id="STtranscriptContent16" class="STtranscriptContent" name="32890">But managing a growing team </span>
<span id="STtranscriptContent17" class="STtranscriptContent" name="34260">became costly and distracting. </span>
<span id="STtranscriptContent18" class="STtranscriptContent" name="36880">So John tried a company that </span>
<span id="STtranscriptContent19" class="STtranscriptContent" name="38200">used automated speech to text </span>
<span id="STtranscriptContent20" class="STtranscriptContent" name="39830">
<span id="STtranscriptContent21" class="STtranscriptContent" name="43420">About 3 out of every 10 </span>
<span id="STtranscriptContent22" class="STtranscriptContent" name="44740">words were wrong, which they required manual editing. </span>
<span id="STtranscriptContent23" class="STtranscriptContent" name="48030">He then tried a company that </span>
<span id="STtranscriptContent24" class="STtranscriptContent" name="49250">leveraged crowd sourcing. But the </span>
<span id="STtranscriptContent25" class="STtranscriptContent" name="50940">transcribers were anonymous, and </span>
<span id="STtranscriptContent26" class="STtranscriptContent" name="53010">couldn't be properly trained to </span>
<span id="STtranscriptContent27" class="STtranscriptContent" name="54420">address his specific business requirement. </span>
<span id="STtranscriptContent28" class="STtranscriptContent" name="56970">There had to be a smarter  </span>
<span id="STtranscriptContent29" class="STtranscriptContent" name="58120">
<span id="STtranscriptContent30" class="STtranscriptContent" name="61360">But, how? </span>
<span id="STtranscriptContent31" class="STtranscriptContent" name="62860">Introducing SpeakerText, the </span>
<span id="STtranscriptContent32" class="STtranscriptContent" name="64720">most advanced and scalable solution  </span>
<span id="STtranscriptContent33" class="STtranscriptContent" name="66760">to make your video accessible, discoverable, and actionable. </span>
<span id="STtranscriptContent34" class="STtranscriptContent" name="70760">SpeakerText combines innovative technology </span>
<span id="STtranscriptContent35" class="STtranscriptContent" name="73140">with talented and well trained </span>
<span id="STtranscriptContent36" class="STtranscriptContent" name="74370">people to help organizations improve </span>
<span id="STtranscriptContent37" class="STtranscriptContent" name="76030">accessibility, and maximize ROI </span>
<span id="STtranscriptContent38" class="STtranscriptContent" name="77790">
<span id="STtranscriptContent39" class="STtranscriptContent" name="81180">Inspired by the efficiency of Henry Ford's assembly line, </span>
<span id="STtranscriptContent40" class="STtranscriptContent" name="84300">SpeakerText is literally built </span>
<span id="STtranscriptContent41" class="STtranscriptContent" name="86040">as a factory in the cloud, </span>
<span id="STtranscriptContent42" class="STtranscriptContent" name="87810">with production lines custom built for different applications. </span>
<span id="STtranscriptContent43" class="STtranscriptContent" name="90910">Each video is sliced into a 10 </span>
<span id="STtranscriptContent44" class="STtranscriptContent" name="92300">second clips, which are </span>
<span id="STtranscriptContent45" class="STtranscriptContent" name="93610">intelligently dispatched to a curated </span>
<span id="STtranscriptContent46" class="STtranscriptContent" name="95530">
<span id="STtranscriptContent47" class="STtranscriptContent" name="98420">The clips are then compiled into one minute segments for quality review. </span>
<span id="STtranscriptContent48" class="STtranscriptContent" name="102070">And once the entire transcript is </span>
<span id="STtranscriptContent49" class="STtranscriptContent" name="103660">completed, it's reviewed again to assure high accuracy. </span>
<span id="STtranscriptContent50" class="STtranscriptContent" name="107090">This parallel processing provides </span>
<span id="STtranscriptContent51" class="STtranscriptContent" name="108780">an ultra-fast, accurate, and </span>
<span id="STtranscriptContent52" class="STtranscriptContent" name="110450">affordable transcription in captioning solutions.  </span>
<span id="STtranscriptContent53" class="STtranscriptContent" name="113290">
<span id="STtranscriptContent54" class="STtranscriptContent" name="116010">Now, your video can be discovered by search engines. </span>
<span id="STtranscriptContent55" class="STtranscriptContent" name="118870">Every word is searchable, and people </span>
<span id="STtranscriptContent56" class="STtranscriptContent" name="120400">can jump from the specific segment </span>
<span id="STtranscriptContent57" class="STtranscriptContent" name="122150">and even share quotes from the video as a clip. </span>
<span id="STtranscriptContent58" class="STtranscriptContent" name="125110">Imagine the possibilities when you </span>
<span id="STtranscriptContent59" class="STtranscriptContent" name="126960">combine powerful technology in a </span>
<span id="STtranscriptContent60" class="STtranscriptContent" name="128890">managed workforce of thousands dedicated </span>
<span id="STtranscriptContent61" class="STtranscriptContent" name="130950">
<span id="STtranscriptContent62" class="STtranscriptContent" name="133220">Contact the SpeakerText transcription specialists, today.</span>
</div>
<div class="STtranscriptStatus"></div>
</div>
</div>
<div class="STplayerBase">
<div class="STmessagePane" style="width: 423px;"></div>
</div>
</div>
</div>

</body>
</html>

**Comment by colby-swandale** [comment]
im not sure how this relates to this project sorry? can you provide a bit more clarification.

**Comment by karunakarkarna** [comment]
I solved this issue and thanks  for you replay...
