### ISSUE TITLE
Video Automatic (“Pull”) upload support

### ISSUE THREAD

**Issue by iurifq** [matthooks/vimeo#69]
In [Vimeo's Upload API](https://developer.vimeo.com/api/upload/videos) there are three possible approaches.
- Post
- Streaming
- Automatic (“Pull”)

As I understood from this gem's code, it has support to just the first two. Is there a specific reason for that or the third was just not implemented yet?

**Comment by matthooks** [comment]
Pull wasn't around when I created the gem. Feel free to submit a PR if you've got a take on how to implement it!
